# TODOs

* PCA to see which feature has how much influence
* implement scoring function, eating food gives plus, getting smaller distance to food gives plus, reducing distance to enemy wolf gives minus etc.?

In [72]:
import pandas as pd
from sklearn import tree, naive_bayes, svm
import ast
import math
import pickle
import os
import glob

## Use the same config as in the later game

In [2]:
#[General_Constants]
FIELD_WIDTH = 19
FIELD_HEIGHT = 15

#[Game_Constants]
NO_ITERATIONS = 100
MAX_CALC_TIME = 100000

#[Field_Constants]
CELL_EMPTY = '.'
CELL_SHEEP_1 = 'S'
CELL_SHEEP_1_d = 'U'
CELL_WOLF_1 = 'W'
CELL_SHEEP_2 = 's'
CELL_SHEEP_2_d = 'u'
CELL_WOLF_2 = 'w'
CELL_GRASS = 'g'
CELL_RHUBARB = 'r'
CELL_FENCE = '#'


#[Movements]
MOVE_NONE = 0
MOVE_UP = -1
MOVE_DOWN = 1
MOVE_LEFT = -2
MOVE_RIGHT = 2

#[Awards]
AWARD_RHUBARB = 5
AWARD_GRASS = 1

# Load data

Load all games into one dataframe

In [3]:
# path = "../example_player/training_data" 
# all_files = glob.glob(path + "/*.csv")

# li = []

# for filename in all_files:
#     df = pd.read_csv(filename, index_col=None, header=0, keep_default_na=False)    
#     df['game'] = filename
#     li.append(df)

# frame = pd.concat(li, axis=0, ignore_index=True)

In [4]:
path = "../example_player/training_data/subset" 
all_files = glob.glob(path + "/*.csv")   

training_data = []

#load the data into a pandas frames
for file in all_files:
    game_data = pd.read_csv(file,index_col=False)
    reason = game_data.iloc[-1][6]
    
    #if the reason is found, add it to each line to fill out the blanks
    if type(reason) is str:
        for index,row in game_data.iterrows():
            game_data.loc[index,'reason'] = reason

    #else there was no reason, implying the game reached the number of iterations
    else:
        for index,row in game_data.iterrows():
            game_data.loc[index,'reason'] = 'max_iterations'    
    
    training_data.append(game_data)

#preview the final 5 lines
training_data[-1].head()

field_before  \
0  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
1  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
2  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
3  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
4  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   

                                         field_after   turn_made_by  \
0  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...  player1 sheep   
1  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...  player2 sheep   
2  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...  player1 sheep   
3  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...  player2 sheep   
4  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   player1 wolf   

   move_made  score1  score2        reason  
0          2       0       0  sheep1 eaten  
1         -1       0       0  sheep1 eaten  
2          2       0       0  sheep1 eaten  
3         -1       0       0  sheep1 eaten  
4          2       0       0  sheep1 eaten

## Drop unneeded rows

Use only where:
* shows winner movement
* ending reason is '' (ended because of max iterations) or sheep eaten

In [167]:
# df_train = frame[((frame.reason == 'sheep1 eaten') 
#                   | (frame.reason == 'sheep2 eaten')
#                   | (frame.reason == ''))]

# df_train = df_train.join(df_train.groupby('game').agg({'score1':'max','score2':'max'}),on='game',rsuffix='_max')

In [168]:
# def is_winner(row):
#     if '1' in row.turn_made_by:
#         comp= row['score1_max'] > row['score2_max']
#     else:
#         comp= row['score2_max'] > row['score1_max']
#     return comp

# df_train = df_train[df_train.apply(lambda row: is_winner(row),axis=1)]

## Generate general use features

position of wolf, sheep, closest food

In [169]:
# sm = df_train[:10]

In [170]:
# def get_pos(row):    
#     y = 0
#     for r in ast.literal_eval(row['field_before']):
#         x = 0
#         for item in r:
#             if item == 'W':
#                 w1_x = x
#                 w1_y = y
#             elif item == 'S':
#                 s1_x = x
#                 s1_y = y
#             elif item == 'w':
#                 w2_x = x
#                 w2_y = y
#             elif item == 's':
#                 s2_x = x
#                 s2_y = y
#             x += 1
#         y += 1
#     return (w1_x,w1_y,s1_x,s1_y,w2_x,w2_y,s2_x,s2_y)

# sm['pos_'] = sm.apply(lambda row: get_pos(row), axis=1)

/home/chris/PAI/Ex2/venv/lib/python3.7/site-packages/ipykernel_launcher.py:22: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [171]:
# sm[['pos_w1_x', 'pos_w1_y', 'pos_s1_x', 'pos_s1_y', 'pos_w2_x', 'pos_w2_y', 'pos_s2_x', 'pos_s2_y']] = pd.DataFrame(sm['pos_'].tolist(), index=sm.index)  

# Feature selection and Instance selection 

## Sheep

calculate x and y distance to wolf and to closest food


In [110]:
def valid_move(new_x, new_y, field, player, is_sheep = True):
    # Neither the sheep nor the wolf, can step on a square outside the map. Imagine the map is surrounded by fences.
    if new_x > FIELD_HEIGHT - 1:
        return False
    elif new_x < 0:
        return False
    elif new_y > FIELD_WIDTH - 1:
        return False
    elif new_y < 0:
        return False

    # Neither the sheep nor the wolf, can enter a square with a fence on.
    if field[new_x][new_y] == CELL_FENCE:
        return False

    if(is_sheep):
        # Sheep can not step on squares occupied by the wolf of the same player.
        # Sheep can not step on squares occupied by the opposite sheep.
        if '1' in player:
            if field[new_x][new_y] == CELL_SHEEP_2 or \
                    field[new_x][new_y] == CELL_WOLF_1 or \
                    field[new_x][new_y] == CELL_WOLF_2:
                return False
        else:
            if field[new_x][new_y] == CELL_SHEEP_1 or \
                    field[new_x][new_y] == CELL_WOLF_2 or \
                    field[new_x][new_y] == CELL_WOLF_1:
                return False
    else:
        # Wolfs can not step on squares occupied by the opponents wolf (wolfs block each other).
        # Wolfs can not step on squares occupied by the sheep of the same player .
        if '1' in player:
            if field[new_x][new_y] == CELL_WOLF_2:
                return False
            elif field[new_x][new_y] == CELL_SHEEP_1:
                return False
        elif figure == CELL_WOLF_2:
            if field[new_x][new_y] == CELL_WOLF_1:
                return False
            elif field[new_x][new_y] == CELL_SHEEP_2:
                return False
    return True

In [148]:
def value_of_move(new_x, new_y,  sheep_position, wolf_position,field, food_goal, player, is_sheep = True):
    if valid_move(new_x, new_y, field, player, is_sheep):
        move_value = 0
                
        # deduct points if moving closer to wolf
#         sf_x_wolf_before = abs(sheep_position[0] - wolf_position[0])
#         sf_y_wolf_before = abs(sheep_position[1] - wolf_position[1])
        sf_x_wolf_after = abs(new_x - wolf_position[0])
        sf_y_wolf_after = abs(new_y - wolf_position[1])
        
        if (sf_x_wolf_after < 3):
            move_value -= 50
#         elif (sf_x_wolf_after > sf_x_wolf_before):
#             move_value += 1
        if (sf_y_wolf_after < 3):
            move_value -= 50
#         elif (sf_y_wolf_after > sf_y_wolf_before): 
#             move_value += 1
         
                  
        if food_goal:
            # set direction of food
            sf_x_food_before = abs(sheep_position[0] - food_goal[0])
            sf_y_food_before = abs(sheep_position[1] - food_goal[1])
            sf_x_food_after = abs(new_x - food_goal[0])
            sf_y_food_after = abs(new_y - food_goal[1])

            if (sf_x_food_after > sf_x_food_before):
                move_value -= 3
            elif (sf_x_food_after < sf_x_food_before):
                move_value += 2
            if (sf_y_food_after > sf_y_food_before):
                move_value -= 3
            elif (sf_y_food_after < sf_y_food_before):
                move_value += 2
        
        return move_value
    else:
        # never even attempt to go there
        return -1000

In [149]:
X_sheep = []
Y_sheep = []
number_moves = 0

for game in training_data:
    
    #we want to learn from the winning player, which is the player with the highest score:
    if game.iloc[-1][4] < game.iloc[-1][5]:
        sheep = 's'
        wolf = 'W'
    
    elif game.iloc[-1][4] > game.iloc[-1][5]:
        sheep = 'S'
        wolf = 'w'
    else:
        continue

    rhubarb = 'r'
    grass = 'g'

    #for each game state in our training data
    for index,row in game.iterrows():

        #we don't want games that ended because of an error or because the sheep commited suicide
        if row['reason'] not in ('sheep1 eaten','sheep2 eaten','max_iterations'):
            continue

        #we want to only learn from sheep
        if row['move_made'] == 'player1 wolf' or row['move_made'] == 'player2 wolf':
            continue
        
        number_moves += 1
        
        #this is the move that we are learning from this game state
        move = row['move_made']

        #create empty feature array for this game state
        game_features = []

        #turn the field from before the move from a string back to a list
        field= ast.literal_eval(row['field_before'])

        #get positions of sheep, wolf and food items
        food = []
        y=0
        for field_row in field:
            x = 0
            for item in field_row:
                if item == sheep:
                    sheep_position = (x, y)
                elif item == wolf:
                    wolf_position = (x, y)
                elif item == rhubarb or item == grass:
                    food.append((x, y))
                x += 1
            y += 1

        # feature 1: x-distance wolf
        sf_x_wolf = sheep_position[0] - wolf_position[0]
        # feature 2: y-distance wolf
        sf_y_wolf = sheep_position[1] - wolf_position[1]

        # determine closest food:
        food_distance = 1000
        food_goal = None
        for food_item in food:
            distance = abs(food_item[0] - sheep_position[0]) + abs(food_item[1] - sheep_position[1])
            if distance < food_distance:
                food_distance = distance
                food_goal = food_item

        # feature 3: x-distance to food
        sf_x_food = 0
        # feature 4: y-distance to food
        sf_y_food = 0               
        if food_goal:
            sf_x_food = sheep_position[0] - food_goal[0]
            sf_y_food = sheep_position[1] - food_goal[1]

#         # feature 5: is going up allowed?
#         sf_up = valid_move(sheep_position[0] - 1, sheep_position[1], field,
#                            row['turn_made_by'], True)
#         # feature 6: is going down allowed?
#         sf_down = valid_move(sheep_position[0] + 1, sheep_position[1], field,
#                              row['turn_made_by'], True)
#         # feature 7: is going right allowed?
#         sf_right = valid_move(sheep_position[0], sheep_position[1] + 1, field,
#                               row['turn_made_by'], True)
#         # feature 8: is going left allowed?
#         sf_left = valid_move(sheep_position[0], sheep_position[1] - 1, field,
#                              row['turn_made_by'], True)
        
        # feature: value of moving up
        sf_v_up = value_of_move(sheep_position[0] - 1, sheep_position[1], sheep_position, wolf_position, field, food_goal,
                           row['turn_made_by'], True)
        # feature: value of moving down
        sf_v_down = value_of_move(sheep_position[0] + 1, sheep_position[1], sheep_position, wolf_position, field, food_goal,
                           row['turn_made_by'], True)
        # feature 9: value of moving right
        sf_v_right = value_of_move(sheep_position[0], sheep_position[1]+1, sheep_position, wolf_position, field, food_goal,
                           row['turn_made_by'], True)
        # feature 9: value of moving left
        sf_v_left = value_of_move(sheep_position[0], sheep_position[1]-1, sheep_position, wolf_position, field, food_goal,
                           row['turn_made_by'], True)
        
#         game_features.append(sf_x_wolf)
#         game_features.append(sf_y_wolf)
#         game_features.append(sf_x_food)
#         game_features.append(sf_y_food)
#         game_features.append(sf_up)
#         game_features.append(sf_down)
#         game_features.append(sf_right)
#         game_features.append(sf_left)
        game_features.append(sf_v_up)
        game_features.append(sf_v_down)
        game_features.append(sf_v_right)
        game_features.append(sf_v_left)

        #add features and move to X_sheep and Y_sheep
        X_sheep.append(game_features)
        Y_sheep.append(move)

#this prints an example of our feature and outcome vector:
print(X_sheep[0])
print(Y_sheep[0])
print(number_moves)

[-3, 2, 2, -3]
2
2992


In [115]:
# # we want to only learn from sheep
# df_sheep = df_train[((df_train.turn_made_by == 'player1 sheep') | (df_train.turn_made_by == 'player2 sheep'))]

# df_sheep['f1'] = 

field_before  \
0       [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
2       [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
6       [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
8       [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
12      [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
14      [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
18      [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
20      [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
24      [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
26      [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
30      [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
32      [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
36      [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
38      [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
42      [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
44      [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
48      [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
50      [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
54      [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
56      [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
60      [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
62      [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
66      [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
68      [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
72      [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
74      [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
78      [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
80      [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
84      [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
86      [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
...                                                   ...   
709082  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
709084  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
709088  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
709090  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
709094  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
709096  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
709100  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
709102  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
709106  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
709108  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
709112  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
709114  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
709118  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
709120  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
709124  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
709126  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
709130  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
709132  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
709136  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
709138  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
709142  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
709144  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
709148  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
709150  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
709154  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
709156  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
709160  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
709162  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
709166  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   
709168  [['.', '.', '.', '.', '.', '.', '.', '.', '.',...   

                                              field_after   turn_made_by  \
0       [['.', '.', '.', '.', '.', '.', '.', '.', '.',...  player1 sheep   
2       [['.', '.', '.', '.', '.', '.', '.', '.', '.',...  player1 sheep   
6       [['.', '.', '.', '.', '.',

In [15]:

# X_sheep = []
# Y_sheep = []
# number_moves = 0

# for game in training_data:

#     # we want to learn from the winning player, which is the player with the highest score:
#     if game.iloc[-1][4] < game.iloc[-1][5]:
#         sheep = 's'
#         wolf = 'W'

#     elif game.iloc[-1][4] > game.iloc[-1][5]:
#         sheep = 'S'
#         wolf = 'w'
#     else:
#         continue

#     rhubarb = 'r'
#     grass = 'g'

#     # for each game state in our training data
#     for index, row in game.iterrows():

#         # we don't want games that ended because of an error or because the sheep commited suicide
#         if row['reason'] not in ('sheep1 eaten', 'sheep2 eaten', 'max_iterations'):
#             continue

#         # we want to only learn from sheep
#         if row['move_made'] == 'player1 wolf' or row['move_made'] == 'player2 wolf':
#             continue

#         number_moves += 1

#         # this is the move that we are learning from this game state
#         move = row['move_made']

#         # create empty feature array for this game state
#         game_features = []

#         # turn the field from before the move from a string back to a list
#         field = ast.literal_eval(row['field_before'])

#         # get positions of sheep, wolf and food items
#         food = []
#         y = 0
#         for field_row in field:
#             x = 0
#             for item in field_row:
#                 if item == sheep:
#                     sheep_position = (x, y)
#                 elif item == wolf:
#                     wolf_position = (x, y)
#                 elif item == rhubarb or item == grass:
#                     food.append((x, y))
#                 x += 1
#             y += 1
#         # feature 1: x-distance wolf
#         s_feature1 = sheep_position[0] - wolf_position[0]
#         # feature 2: y-distance wolf
#         s_feature2 = sheep_position[1] - wolf_position[1]

       
#         # determine closest food:
#         food_distance = 1000
#         food_goal = None
#         for food_item in food:
#             distance = abs(food_item[0] - sheep_position[0]) + abs(food_item[1] - sheep_position[1])
#             if distance < food_distance:
#                 food_distance = distance
#                 food_goal = food_item

#         # feature 3: x-distance to food
#         s_feature3 = 0
#         # feature 4: y-distance to food
#         s_feature4 = 0

#         if food_goal:
#             s_feature3 = sheep_position[0] - food_goal[0]
#             s_feature4 = sheep_position[1] - food_goal[1]

#     game_features.append(s_feature1)
#     game_features.append(s_feature2)
#     game_features.append(s_feature3)
#     game_features.append(s_feature4)

#     # add features and move to X_sheep and Y_sheep
#     X_sheep.append(game_features)
#     Y_sheep.append(move)

this prints an example of our feature and outcome vector:

In [16]:
# print(X_sheep[0])
# print(Y_sheep[0])
# print(number_moves)

[1, 2, 0, 0]
1
229206


## Wolf

Explain here in text which feature you used for the wolf, and which data you used for training.

In [17]:
#construct your features here

# Build Sheep Model

Min-Max-normalizing for all values

In [150]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_sheep_norm=scaler.fit_transform(X_sheep)

PCA (https://stackoverflow.com/questions/50796024/feature-variable-importance-after-a-pca-analysis)

In [151]:
from sklearn import decomposition
pca = decomposition.PCA(n_components=3)
pca.fit(X_sheep_norm)
print(pca.explained_variance_ratio_)
print(abs( pca.components_ ))


[0.75541833 0.18150371 0.04101949]
[[0.47208156 0.51339882 0.50497872 0.50848514]
 [0.88118203 0.29455083 0.24898531 0.2734307 ]
 [0.02067086 0.8052225  0.38047247 0.45434584]]


Split into train and test data

In [155]:
X_sheep

[[-3, 2, 2, -3],
 [-3, 2, 2, -3],
 [-3, 2, 2, -3],
 [-3, 2, 2, -3],
 [-3, 2, 2, -3],
 [-3, 2, 2, -3],
 [-3, 2, 2, -3],
 [-3, 2, 2, -3],
 [-3, 2, 2, -3],
 [-3, 2, 2, -3],
 [-3, 2, 2, -3],
 [-3, 2, 2, -3],
 [-3, 2, 2, -3],
 [-3, 2, 2, -3],
 [-3, 2, 2, -3],
 [-3, 2, 2, -3],
 [-3, 2, 2, -3],
 [-3, 2, 2, -3],
 [-3, 2, 2, -3],
 [-3, 2, 2, -3],
 [-3, 2, 2, -3],
 [-3, 2, 2, -3],
 [-3, 2, 2, -3],
 [-3, 2, 2, -3],
 [-3, 2, 2, -3],
 [-3, -3, 2, -3],
 [-3, -3, 2, -3],
 [-3, -3, 2, -3],
 [-3, -3, 2, -3],
 [-3, -3, 2, -3],
 [-3, -3, -48, -3],
 [-53, -53, -48, -3],
 [-53, -53, -48, -3],
 [-48, -53, -53, -53],
 [-48, -53, -53, -53],
 [-48, -53, -53, -53],
 [-48, -53, -53, -53],
 [-48, -53, -53, -48],
 [-48, -53, -53, -48],
 [-53, -53, -53, -48],
 [-53, -53, -53, -48],
 [-53, -53, -53, -48],
 [-53, -53, -53, -48],
 [-50, -50, -50, -50],
 [-50, -50, -50, -50],
 [-50, -50, -50, -50],
 [-50, -50, -50, -50],
 [-50, -50, -50, -50],
 [-50, -50, -50, -50],
 [-50, -50, -50, -50],
 [-50, -50, -50, -50],
 [-50, 

In [152]:
from sklearn import model_selection
x_train_s, x_test_s, y_train_s, y_test_s = model_selection.train_test_split(X_sheep, Y_sheep, test_size=0.25)

## Train & Test sheep

Allowed algorithms:
* Naive Bayes (GaussianNB, MultinominalNB, ComplementNB, BernoulliNB)
* Decision Tree
* Support Vector Machine (SVC, NuSVC, LinearSVC)

In [129]:
from sklearn.metrics import confusion_matrix
import numpy as np

## Naive Bayes

In [153]:
sheep_NB = naive_bayes.GaussianNB()
# sheep_NB = naive_bayes.MultinomialNB()
# sheep_NB = naive_bayes.ComplementNB()
# sheep_NB = naive_bayes.BernoulliNB()
sheep_NB = sheep_NB.fit(x_train_s,y_train_s)
y_pred_s = sheep_NB.predict(x_test_s)

cm = confusion_matrix(y_test_s, y_pred_s.tolist())
recall = np.diag(cm) / np.sum(cm, axis = 1)
precision = np.diag(cm) / np.sum(cm, axis = 0)

print(cm)
print(np.mean(recall))
print(np.mean(precision))

[[  0   0   0 126  19]
 [  0   0   0 146  29]
 [  0   0   0  71  20]
 [  0   0   0 145  25]
 [  0   0   0 122  45]]
0.2244804508629799
nan


/home/chris/PAI/Ex2/venv/lib/python3.7/site-packages/ipykernel_launcher.py:10: RuntimeWarning: invalid value encountered in true_divide
  # Remove the CWD from sys.path while we load stuff.


## Decision Tree

In [154]:
sheep_tree = tree.DecisionTreeClassifier()
sheep_tree = sheep_tree.fit(x_train_s,y_train_s)
y_pred_s = sheep_tree.predict(x_test_s)

cm = confusion_matrix(y_test_s, y_pred_s.tolist())
recall = np.diag(cm) / np.sum(cm, axis = 1)
precision = np.diag(cm) / np.sum(cm, axis = 0)

print(cm)
print(np.mean(recall))
print(np.mean(precision))

[[60 20  3 20 42]
 [36 33 10 57 39]
 [ 8  5 39 14 25]
 [45 27 15 61 22]
 [31 22 13 24 77]]
0.370167466862855
0.3702890426950149


## SVM

In [132]:
# sheep_svm = svm.SVC()
sheep_svm = svm.NuSVC()
# sheep_svm = svm.LinearSVC()
sheep_svm = sheep_svm.fit(x_train_s,y_train_s)
y_pred_s = sheep_svm.predict(x_test_s)

cm = confusion_matrix(y_test_s, y_pred_s.tolist())
recall = np.diag(cm) / np.sum(cm, axis = 1)
precision = np.diag(cm) / np.sum(cm, axis = 0)

print(cm)
print(np.mean(recall))
print(np.mean(precision))

[[ 18   4  11  12 123]
 [ 18   7   6  19 118]
 [  5   1   3  13  71]
 [ 40   2   8   8  99]
 [ 21   7  10  35  89]]
0.15628114367755488
0.17174106259563718


/home/chris/PAI/Ex2/venv/lib/python3.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


# Train wolf

In [ ]:
# wolf_tree = tree.DecisionTreeClassifier()
# wolf_tree = wolf_tree.fit(X_wolf,Y_wolf)

# Save models to files

Save your models to files here using pickle. Change the [uzhshortname] to your own UZH shortname. This name needs to match the model that you caller in your python player file.

In [118]:
sheep_filename = 'chriweb_sheep_model.sav'
# wolf_filename = 'chriweb_wolf_model.sav'

pickle.dump(sheep_svm,open(sheep_filename,'wb'))
# pickle.dump(wolf_tree,open(wolf_filename,'wb'))